### PR TITLE
Ignore mica sybase warning if no access file

### PR DESCRIPTION
**Pull request by jeanconn**
Ignore mica sybase warning if no access file.

### CODE REVIEW

**Comment by jeanconn** [comment]
It might be a reasonable balance to leave the warning in the unit tests but to cut complaints about it from ska_testr outputs with the log check mechanism.

**Comment by taldcroft** [comment]
I don't think this will work since the warnings are in 4 places:
```
ValueError: Found matches in check_files:
'warning' matched at test_unit.log:156 :: [33m=============================== warnings summary ===============================[0m
'warning' matched at test_unit.log:158 :: /export/jgonzale/github-workflows/miniconda3-shiny/envs/ska3-flight-2021.1rc2/lib/python3.8/site-packages/mica/report/tests/test_write_report.py:19: UserWarning: On HEAD but no sybase access. Run ska_envs or define SYBASE/SYBASE_OCS
'warning' matched at test_unit.log:161 :: -- Docs: https://docs.pytest.org/en/latest/warnings.html
'warning' matched at test_unit.log:163 :: [33m============ [32m46 passed[0m, [33m[1m1 skipped[0m, [33m[1m1 warning[0m[33m in 1086.04s (0:18:06)[0m[33m =============[0m
Bash-17:50:26>
```
The warning suppressing has to take place upstream at the pytest level. The ska_testr warning suppression was designed more for regression logs or things like the `*FAIL*` MSIDs.

But more fundamentally, if we are allowing our automated CI and final check of a Ska release to silently ignore then warning, then why purposely issue it in the package?

**Comment by jeanconn** [comment]
Huh.  I guess the problem with my checking the change here is that I'm getting 'pass' as the kadi user before the change.

With regard to: "But more fundamentally, if we are allowing our automated CI and final check of a Ska release to silently ignore the warning, then why purposely issue it in the package?".  We've gone back and for on this, but for me, as developer, I just make sure to run the unit tests on Linux before making a PR if that PR hits the mica.report making code.  Perhaps updating the PR template for that  + this change is reasonable.  I would just like to see our tests PASS if "appropriate" testing has been done and there are no new issues.

**Comment by jeanconn** [comment]
Superseded by https://github.com/sot/mica/pull/256

**Pull request closed without merging**
