### PR TITLE
ignore some specific passing tests in cheta post_check_logs.py

### PR DESCRIPTION
**Pull request by javierggt**
## Description

ignore some specific passing testsin cheta post_check_logs.py

## Testing

- [ ] Functional testing

Fixes #

### CODE REVIEW

**Comment by jeanconn** [comment]
Which installation should I test this against?

**Review by jeanconn — CHANGES_REQUESTED** [review]
This is probably fine but my comment was that I wasn't sure how to test it.

**Review by taldcroft — APPROVED** [review]
LGTM

**Review by jeanconn — APPROVED** [review]
This is fine.  I didn't run tests.

**Pull request merged**
