### PR TITLE
Use a longer form version id for outputs including platform and machine

### PR DESCRIPTION
**Pull request by jeanconn**

### CODE REVIEW

**Comment by jeanconn** [comment]
Having both platform and machine ends up being a bit redundant, but I found it a good reminder.

**Comment by jeanconn** [comment]
Though I've forgotten, is $HOST still cool on bash?

**Comment by jeanconn** [comment]
Eh, I guess it wouldn't run in the /bin/sh script if it weren't supported.

**Comment by taldcroft** [comment]
Empirically I have found that $HOST just gives `''` in the output, i.e. `2.18-r743-a0c0111_x86_64_`.  Did this work for you?  Maybe works on CentOS-5 but not 6?

**Comment by jeanconn** [comment]
I probably should have just marked this as a local WIP.  I just wanted to get up all the changes as PRs for now.  

My ska_testr output directory is littered with fido and unagi postfixed directories (fido 6, unagi 5), so I don't think it is a 5 vs 6 issue.  It might be a shell issue as even if I get into a bash shell, I started with a csh.

**Comment by taldcroft** [comment]
How about `$HOSTNAME`.  That seems to work for me on bash and tcsh.

**Comment by jeanconn** [comment]
IIRC, `hostname` might be more reliable if this actually has value.

**Comment by jeanconn** [comment]
Oops, simultaneous comment, not sure if the env variable or the command is more of a sure thing.

**Comment by taldcroft** [comment]
Your guess is better than mine.

**Comment by jeanconn** [comment]
I'll push a change to use ${HOSTNAME} for now.

**Pull request merged**
