### PR TITLE
Use the explicit OCAT URL when checking whether CDA is accessible

### PR DESCRIPTION
**Pull request by javierggt**
## Description

This is to skip some tests when CDA is not accessible.

## Testing

- [ ] Functional testing

### CODE REVIEW

**Comment by taldcroft** [comment]
So I'm guessing there was a failure and the CDA site was accessible but not that URL?

**Comment by javierggt** [comment]
Yes, I guess that was because they changed something on the servers about a week and a half or two ago.

**Comment by taldcroft** [comment]
So probably this is broken too:
https://github.com/sot/mica/blob/756a27caaf593719130bf470d6768605481f37d1/mica/archive/tests/test_cda.py#L13

We would be skipping all CDA tests always.

**Comment by taldcroft** [comment]
Although actually that test does not check the return status, so maybe it is still working if there is no exception.

**Comment by jeanconn** [comment]
"So I'm guessing there was a failure and the CDA site was accessible but not that URL?"  In response to that question I think it was the inverse?  The test was being skipped because the generic URL did not work.

**Comment by jeanconn** [comment]
The mica thread was working IIRC because requests didn't handle the 403 as an exception, but urllib in testr did...

**Review by taldcroft — APPROVED** [review]
LGTM

**Pull request merged**
