### PR TITLE
Add hopper to tests

### PR DESCRIPTION
**Pull request by jeanconn**
Add hopper to tests

### CODE REVIEW

**Review by taldcroft — APPROVED** [review]

**Comment by jeanconn** [comment]
I think this breaks until the hopper update goes; not sure if the dashboard
tests are pulling from master daily.

**Comment by taldcroft** [comment]
The dashboard tests are always running from latest masters. Can you clarify what "the hopper update goes" means?

**Comment by jeanconn** [comment]
https://github.com/sot/hopper/pull/20

**Comment by taldcroft** [comment]
OK we should be fine since https://github.com/sot/hopper/pull/20 is in master already.

**Pull request merged**
