### PR TITLE
Add find_attitude

### LINKED ISSUE #17: Add find_attitude on HEAD testing
This is a long-running test (several minutes).

### PR DESCRIPTION
**Pull request by jeanconn**
Add find_attitude

```
***      find_attitude         test_unit_head.py   pass ***
***      find_attitude   post_check_logs_head.py   pass ***
```

Closes #17

### CODE REVIEW

**Comment by jeanconn** [comment]
I haven't checked to see if this should be HEAD only per #17

**Comment by taldcroft** [comment]
I think for now we can leave this as HEAD only.  It depends on a big file, takes a few minutes, and is only critical that it run on linux.  Of course tests do pass on my Mac, and the run time is substantially lower (107 sec vs. 370 sec on kady).

**Comment by jeanconn** [comment]
The update to include Ska.Sun reminded me of this.  It looks to me like the find_attitude tests don't pass on HEAD in flight; I don't remember where we left that.

**Comment by jeanconn** [comment]
Looks like this will have a handful of deprecation warnings on ska3-next; I'm not sure where we want to silence them.

**Comment by taldcroft** [comment]
@jeanconn - when you say the tests "don't pass", are those real failures or just warnings that turn into testr fails?

**Comment by jeanconn** [comment]
For me, the debug logging error also showed that it was calling the installed module, so I changed to a relative import.  And then the relative import didn't work because there was no __init__.py in the test directory.  And then there was https://github.com/sot/find_attitude/pull/16 .

**Review by taldcroft — COMMENTED** [review]
Looks good in theory. Needs documentation of functional testing that it actually works as intended on HEAD.

**Comment by jeanconn** [comment]
Gotcha.  I thought not putting the "I actually ran this" section in the PR template for ska_testr was a choice at this point.  I haven't run all of the other ska_testr tests on not-HEAD with the standalone template, so that's untested.  I can confirm the testing calls the 6 tests in find_attitude appropriately and updated the description with the summary:
```
============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-6.2.0, py-1.9.0, pluggy-0.13.1 -- /proj/sot/ska3/flight/bin/python
rootdir: /proj/sot/ska/jeanproj/git/find_attitude, configfile: pytest.ini
collected 6 items                                                              

find_attitude/tests/test_find_attitude.py::test_overlapping_distances 2022-03-03 10:29:01,972 Using AGASC pairs file /proj/sot/ska3/flight/data/find_attitude/distances.h5
```

**Comment by taldcroft** [comment]
> I thought not putting the "I actually ran this" section in the PR template for ska_testr was a choice at this point.

Not to my knowledge. I think this repo just didn't get hit by the global template updates that @javierggt did. In any case, every PR description should include documentation of testing (apart from obvious cases where that really doesn't make sense). Yes, the bar is getting higher.

**Review by taldcroft — APPROVED** [review]

**Comment by jeanconn** [comment]
Regarding "Yes, the bar is getting higher.", I'm not 100% convinced we need to keep moving all the bars.  Verifying the right things are tested should be a high bar in the individual packages.  Just adding package tests in ska_testr... an unversioned/non-installed thing, doesn't seem to require a really high standard.  But if you just want confirmation that due diligence was done, since it was done, no reason not to add it to the notes.

**Pull request merged**
